services:
  service:
    build:
      context: service
    networks:
      app-network:

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config.d:/etc/nginx/conf.d:ro
      - ./nginx/data:/data/:ro
    depends_on:
      service:
        condition: service_started
    ports:
      - 80:80
    networks:
      app-network:

networks:
  app-network:
